const getFilterOptions = () => {
	return {
		numberOfPeople: [1, 2],
		roomsWanted: [1, 2],
		rooms: {
			spec: "Includes",
			criteria: {
				residenceArea: [
					"Orchard Commons",
					"Place Vanier",
					"Totem Park",
					"Brock Commons – Tallwood House",
					"Exchange",
					"Fairview Crescent",
					"Fraser Hall",
					"Iona House",
					"Marine Drive",
					"Ponderosa Commons",
					"Ritsumeikan-UBC House",
					"tə šxʷhəleləm̓s tə k̓ʷaƛ̓kʷəʔaʔɬ",
					"Thunderbird",
					"Walter Gage",
					"Acadia Park",
					"Green College",
					"St. John's College",
				],

				generalInfo: {
					residenceType: [
						"First Year",
						"Upper Year",
						"Student Families",
						"Graduate Colleges",
					],
					session: ["Year Round", "Winter Session", "Summer Session"],
				},

				roomInfo: {
					room: [
						"Shared Room",
						"Connected Single Room",
						"Single Traditional Room",
						"Six Bedroom Suite",
						"Four Bedroom Suite",
						"Three Bedroom Suite",
						"Two Bedroom Suite",
						"One Bedroom Suite",
						"Studio Suite",
						"Nano Suite",
						"Townhouse",
					],
					floor: {
						spec: "Interval",
						criteria: [1, "Infinity"],
					},
					washroom: ["Private", "Communal"],
				},

				eligibilityInfo: {
					minimumAge: [1, 18, 19],
					allowedGender: ["Male", "Female", "Any"],
				},
			},
		},
	};
};

const getOfferJSONSample = () => {
	return {
		_id: "6283aa18a8792c8e94d2270c",
		numberOfPeople: 2,
		roomsWanted: 2,
		rooms: [
			{
				residenceArea: "Totem Park",
				generalInfo: {
					session: "Winter Session",
					_id: "6283aa18a8792c8e94d2270e",
					residenceType: "First Year",
				},
				roomInfo: {
					room: "Shared Room",
					floor: 1,
					washroom: "Communal",
					building: "Nootka House",
					_id: "6283aa18a8792c8e94d2270f",
				},
				eligibilityInfo: {
					allowedGender: "Male",
					_id: "6283aa18a8792c8e94d22710",
					minimumAge: 1,
				},
				_id: "6283aa18a8792c8e94d2270d",
			},
			{
				residenceArea: "Orchard Commons",
				generalInfo: {
					session: "Winter Session",
					_id: "6283aa18a8792c8e94d2270e",
					residenceType: "First Year",
				},
				roomInfo: {
					room: "Shared Room",
					floor: 1,
					washroom: "Communal",
					building: "Bartlett House",
					_id: "6283aa18a8792c8e94d2270f",
				},
				eligibilityInfo: {
					allowedGender: "Male",
					_id: "6283aa18a8792c8e94d22710",
					minimumAge: 1,
				},
				_id: "6283aa18a8792c8e94d2270d",
			},
		],
		preference: [
			{
				residenceArea: [
					"Orchard Commons",
					"Totem Park",
					"Exchange",
					"Fraser Hall",
				],
				roomInfo: {
					room: [
						"Shared Room",
						"Connected Single Room",
						"Single Traditional Room",
						"Six Bedroom Suite",
						"Four Bedroom Suite",
						"Three Bedroom Suite",
						"Two Bedroom Suite",
						"One Bedroom Suite",
						"Studio Suite",
						"Nano Suite",
						"Townhouse",
					],
					floor: {
						spec: "Interval",
						criteria: [1, 9],
						_id: "6283aa18a8792c8e94d22713",
					},
					washroom: ["Private", "Communal"],
					_id: "6283aa18a8792c8e94d22712",
				},
				_id: "6283aa18a8792c8e94d22711",
				generalInfo: {
					residenceType: ["First Year", "Upper Year"],
					session: ["Year Round"],
					_id: "6283aa18a8792c8e94d22714",
				},
				eligibilityInfo: {
					allowedGender: ["Female", "Any"],
					_id: "6283aa18a8792c8e94d22715",
					minimumAge: {
						spec: "Interval",
						criteria: [1, 17],
						_id: "6283aa18a8792c8e94d22716",
					},
				},
			},
		],
		dateCreated: "2022-05-17T13:58:48.456Z",
		user: { _id: "62877589252e1f138123225e", username: "Stankursters" },
		additionalInformation: "contact me at my Instagram @whatever",
		__v: 0,
	};
};

const getResidences = () => {
	return {
		residences: [
			{
				name: "Orchard Commons",
				type: "First Year",
				sessions: ["Winter Session"],
				rooms: ["Connected Single Room", "Shared Room"],
				buildings: ["Braeburn House", "Bartlett House"],
				minimumAge: 1,
			},
			{
				name: "Place Vanier",
				type: "First Year",
				sessions: ["Winter Session"],
				rooms: ["Single Traditional Room", "Shared Room"],
				buildings: [
					"Ross House",
					"MacKenzie House",
					"Hamber House",
					"Okanagan House",
					"Kootenay House",
					"Sherwood Lett House",
					"Tweedsmuir House",
					"Cariboo House",
					"Robson House",
					"Tec De Monterrey House",
					"Korea-UBC House",
					"Mawdsley House",
				],
				minimumAge: 1,
			},
			{
				name: "Totem Park",
				type: "First Year",
				sessions: ["Winter Session"],
				rooms: [
					"Single Traditional Room",
					"Shared Room",
					"Connected Single Room",
				],
				buildings: [
					"Kwakiutl House",
					"Shushwap House",
					"q̓ələχən House",
					"həm̓ləsəm̓ House",
					"Nootka House",
					"Dene House",
					"Haida House",
					"Salish House",
					"c̓əsnaʔəm House",
				],
				minimumAge: 1,
			},
			{
				name: "Brock Commons – Tallwood House",
				type: "Upper Year",
				sessions: ["Year Round"],
				rooms: ["Studio Suite", "Four Bedroom Suite"],
				buildings: ["Tallwood House"],
				minimumAge: 19,
			},
			{
				name: "Exchange",
				type: "Upper Year",
				sessions: ["Year Round"],
				rooms: [
					"Nano Suite",
					"Studio Suite",
					"One Bedroom Suite",
					"Townhouse",
					"Two Bedroom Suite",
					"Four Bedroom Suite",
				],
				buildings: [],
				minimumAge: 19,
			},
			{
				name: "Fairview Crescent",
				type: "Upper Year",
				sessions: ["Winter Session", "Summer Session"],
				rooms: [
					"One Bedroom Suite",
					"Four Bedroom Suite",
					"Six Bedroom Suite",
				],
				buildings: [],
				minimumAge: 19,
			},
			{
				name: "Fraser Hall",
				type: "Upper Year",
				sessions: ["Year Round"],
				rooms: ["Six Bedroom Suite"],
				buildings: [],
				minimumAge: 19,
			},
			{
				name: "Iona House",
				type: "Upper Year",
				sessions: ["Year Round"],
				rooms: [
					"Studio Suite",
					"One Bedroom Suite",
					"Two Bedroom Suite",
				],
				buildings: [],
				minimumAge: 19,
			},
			{
				name: "Marine Drive",
				type: "Upper Year",
				sessions: ["Year Round", "Winter Session"],
				rooms: [
					"Studio Suite",
					"Two Bedroom Suite",
					"Three Bedroom Suite",
					"Four Bedroom Suite",
				],
				buildings: [
					"Marine Drive 1",
					"Marine Drive 2",
					"Marine Drive 4",
					"Marine Drive 5",
					"Marine Drive 6",
				],
				minimumAge: 19,
			},
			{
				name: "Ponderosa Commons",
				type: "Upper Year",
				sessions: ["Year Round", "Winter Session", "Summer Session"],
				rooms: [
					"Studio Suite",
					"Two Bedroom Suite",
					"Four Bedroom Suite",
				],
				buildings: [
					"Arbutus House",
					"Maple House",
					"Spruce House",
					"Cedar House",
					"Oak House",
				],
				minimumAge: 19,
			},
			{
				name: "Ritsumeikan-UBC House",
				type: "Upper Year",
				sessions: ["Winter Session"],
				rooms: ["Four Bedroom Suite"],
				buildings: [],
				minimumAge: 18,
			},
			{
				name: "tə šxʷhəleləm̓s tə k̓ʷaƛ̓kʷəʔaʔɬ",
				type: "Upper Year",
				sessions: ["Year Round", "Winter Session"],
				rooms: ["Studio Suite", "Four Bedroom Suite"],
				buildings: [
					"q̓əlɬaləməcən leləm̓ (Orca House)",
					"qʷta:yθən leləm̓ (Sturgeon House)",
					"sɬewət̕ leləm̓ (Herring House)",
					"təməs leləm̓ (Sea Otter House)",
					"sqimək̓ʷ leləm̓ (Octopus House)",
				],
				minimumAge: 19,
			},
			{
				name: "Thunderbird",
				type: "Upper Year",
				sessions: ["Year Round"],
				rooms: [
					"Studio Suite",
					"One Bedroom Suite",
					"Two Bedroom Suite",
					"Four Bedroom Suite",
				],
				buildings: [
					"1000 Block - Cassiar",
					"2000 Block - Monashee",
					"3000 Block - Selkirk",
					"4000 Block - Coast",
					"5000 Block - Hazelton",
				],
				minimumAge: 19,
			},
			{
				name: "Walter Gage",
				type: "Upper Year",
				sessions: ["Winter Session"],
				rooms: [
					"Studio Suite",
					"One Bedroom Suite",
					"Six Bedroom Suite",
				],
				buildings: [
					"Gage Apartments",
					"South Tower",
					"North Tower",
					"East Tower",
				],
				minimumAge: 19,
			},
			{
				name: "Acadia Park",
				type: "Student Families",
				sessions: ["Year Round"],
				rooms: [
					"One Bedroom Suite",
					"Two Bedroom Suite",
					"Three Bedroom Suite",
					"Four Bedroom Suite",
				],
				buildings: [
					"Presidents Row",
					"Acadia Park Townhouses",
					"Acadia House",
					"Sopron House",
					"Point Grey Apartments",
					"Spirit Park Apartments",
					"Acadia Park Highrise",
				],
				minimumAge: 1,
			},
			{
				name: "Green College",
				type: "Graduate Colleges",
				sessions: ["Year Round"],
				rooms: ["Single Traditional Room", "Studio Suite"],
				buildings: [],
				minimumAge: 19,
			},
			{
				name: "St. John's College",
				type: "Graduate Colleges",
				sessions: ["Year Round"],
				rooms: ["Single Traditional Room", "One Bedroom Suite"],
				buildings: [],
				minimumAge: 19,
			},
		],
	};
};
export { getFilterOptions, getOfferJSONSample, getResidences };
